Hw6
Minkerr/FSharpHomeworks pull request #10
Opened 2024-05-30 09:18 UTC by Minkerr

2024-05-30 12:03 UTC, Minkerr commented
В задании с вычислениями я не придумал ничего лучше, чем бросать исключение, так как условие требует, чтобы считалось z = x + y. То есть мы должны получать в x и y что-то, что умеет складываться, а не option, например.

2024-05-30 20:01 UTC, yurii-litvinov requested changes

2024-05-30 20:01 UTC, yurii-litvinov commented on Homework6/Homework6.Tests/Program.fs
> +    let main _ = 0
Это не нужно, можно GenerateProgramFile в true поставить и тогда main сам сгенерится перед компиляцией. Шаблон по умолчанию почему-то этого не делает, но легко поправить

2024-05-30 20:01 UTC, yurii-litvinov commented on Homework6/Homework6.Tests/RoundingTest.fs
> +    act + 0.001 |> should greaterThan 0.048
Есть матчер equalWithin

2024-05-30 20:01 UTC, yurii-litvinov commented on Homework6/Homework6.sln.DotSettings.user
> +﻿<wpf:ResourceDictionary xml:space="preserve" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:s="clr-namespace:System;assembly=mscorlib" xmlns:ss="urn:shemas-jetbrains-com:settings-stora
Этот файл не надо в git выкладывать, .user должен быть в gitignore

2024-05-30 20:01 UTC, yurii-litvinov commented on Homework6/Homework6.sln.DotSettings.user
> +  &lt;Project Location="C:\Users\valen\RiderProjects\Homeworks\Homework6\Homework6.Tests" Presentation="&amp;lt;Homework6.Tests&amp;gt;" /&gt;&#xD;
Иначе мы все узнаем, где у Вас домашняя папка или, чего доброго, что Вы сидите на Windows :)

2024-05-30 20:01 UTC, yurii-litvinov commented on Homework6/Homework6/Program.fs
> +        f x
Не-а, так промежуточные вычисления будут делаться с максимальной точностью, что несколько противоречит условию (представьте, что мы хотим просимулировать восьмибитный компьютер, например — все вычисления должны округляться, потому что точные промежуточные результаты в регистр не лезут).

2024-05-30 20:01 UTC, yurii-litvinov commented on Homework6/Homework6/Program.fs
> +type RoundingBuilder(accuracy : int) =
И комментарии бы неплохо

2024-05-30 20:01 UTC, yurii-litvinov commented on Homework6/Homework6/Program.fs
> +    let TryParseNumber (str : string) =
let-определения по традиции со строчной

2024-05-30 20:01 UTC, yurii-litvinov commented on Homework6/Homework6/Program.fs
> +        | _ -> raise (IncorrectInputString("String should be a number"))
Весь пойнт монад в том, чтобы не бросать исключения, так что не-а, так не пойдёт

2024-05-30 20:01 UTC, yurii-litvinov commented on Homework6/Homework6/Program.fs
> +        f (TryParseNumber x)
Так по образу и подобию maybe-монады: если всё хорошо, внутри число, которое можно распаковать и складывать в своё удовольствие, если плохо, то считать дальше уже не надо.

2024-05-31 20:21 UTC, DedSec256 commented on Homework6/Homework6/Program.fs
> +/// </summary>
```suggestion
/// Monad for rounding calculation results with float 
```

2024-05-31 20:22 UTC, DedSec256 commented on Homework6/Homework6.Tests/RoundingTest.fs
> +            let! a = 2.0 / 12.0
можно следующей строчкой поставить ассерт, чтобы проверить, что в `a` действительно округленное значение

2024-06-24 12:53 UTC, merged